# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 11
          # Java distribution. See the list of supported distributions in README file
          distribution: 'temurin'
          # Name of the build platform to cache dependencies. It can be "maven" or "gradle".
          cache: maven # optional
      - name: Install the dependencies & run the tests
        working-directory: ./
        run: mvn clean test package
          
#      - name: jacoco-reporter
#        # You may pin to the exact commit or the version.
#        # uses: PavanMudigonda/jacoco-reporter@d015c4a09637192cc838fdce7c01c36a84247e41
#        uses: PavanMudigonda/jacoco-reporter@v4.5
#        with:
#          # Path to the JaCoCo coverage results file which will be used to generate a report. The only coverage results format supported is the JaCoCo XML schema.
#          coverage_results_path: .documentation/jacoco-report.xml
          
      - name: Official SonarQube Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        uses: SonarSource/sonarqube-scan-action@v1.1.0
        
      - name: SonarQube Quality Gate Check
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarqube-quality-gate-action@15767f0e4eb489cfdd989dc717fa78c038d0de8a
        uses: SonarSource/sonarqube-quality-gate-action@v1.0.0
        with:
          # Location of the scanner metadata report file
          scanMetadataReportFile: .documentation/report-task.txt
          
      - name: Deploy Javadoc
        # You may pin to the exact commit or the version.
        # uses: MathieuSoysal/Javadoc-publisher.yml@fd508f6228509c8fb511feb5cc0c0f9ac146070f
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.0.4
        with:
          # Java version inside your project
          java-version: 11 # default is 17
          # Branch where the javadoc is hosted
          javadoc-branch: main # default is javadoc
          # Directory where the javadoc contents should be stored
          target-folder: .documentation/JAVADOC/
        
        
          
          
